require(qrmdata)
data("ZCB_US")
last(ZCB_US,'1 year')
last(ZCB_US,'1 month')
require(qrmtools)
require(qrm)
require(ustyc)
require(termstrc)
group <- c("GERMANY", "AUSTRIA")
require(ycinterextra)
